### ISSUE TITLE
显示一行日志的详细信息

### ISSUE THREAD

**Issue by zzongqi** [compilelife/loginsight#10]
一行日志太长了 有的时候需要横向拖动.然后再把他拖动回去. 是否可以有效利用时间线那块地方点击到日志的时候,在那块地方显示这条日志的详细情况?

**Comment by compilelife** [comment]
嗯，这个要支持，我规划下，看看怎么设计合适

**Comment by compilelife** [comment]
我设想了几种操作方式都不是很理想。

看来“自动折行”的显示还是得想办法支持上，这才是"正常“的长行查看方法

**Comment by compilelife** [comment]
v1.4.1已支持折行显示。
