### ISSUE TITLE
打开一个10.5MB的文件，搜索不到指定内容（实际存在）

### ISSUE THREAD

**Issue by heyhachi0** [compilelife/loginsight#13]
log文件包含108500行内容，搜索位于底部的字符串时（内容：“xxxxx: ”），无法找到该字符串

**Comment by compilelife** [comment]
链接：https://pan.baidu.com/disk/main#/transfer/send?surl=AAoAAAAAAAXCTQ

你好，可以将有问题的日志文件转发到我的网盘吗？

**Comment by heyhachi0** [comment]
> 链接：https://pan.baidu.com/disk/main#/transfer/send?surl=AAoAAAAAAAXCTQ
> 
> 你好，可以将有问题的日志文件转发到我的网盘吗？

很抱歉，日志包含了一些敏感信息，因此没有办法提供给你。
后续我尝试复现，发现：
1. 在关闭大小写匹配后出现过一次上述问题

但具体的触发条件仍然不明确，如果后续出现此类问题，我会在此跟进并通知你。

**Comment by compilelife** [comment]
> > 链接：https://pan.baidu.com/disk/main#/transfer/send?surl=AAoAAAAAAAXCTQ
> > 你好，可以将有问题的日志文件转发到我的网盘吗？
> 
> 很抱歉，日志包含了一些敏感信息，因此没有办法提供给你。
> 后续我尝试复现，发现：
> 
> 1. 在关闭大小写匹配后出现过一次上述问题
> 
> 但具体的触发条件仍然不明确，如果后续出现此类问题，我会在此跟进并通知你。

好的，我猜测可能是strnstr对于中文支持有问题

**Comment by compilelife** [comment]
2.0.0版本进行了大幅改动，应该修复了。
