### ISSUE TITLE
过滤输入框无法粘贴文本

### ISSUE THREAD

**Issue by itzhoujun** [compilelife/loginsight#16]
<img width="643" alt="image" src="https://github.com/compilelife/loginsight/assets/6897671/ee09ad2d-7114-4599-a639-886a3e0599bc">

**Comment by compilelife** [comment]
我这边测了Linux和Win10正常，你的操作系统是？

**Comment by itzhoujun** [comment]
> 

macos m1

**Comment by itzhoujun** [comment]
日志选中也没法command + c来复制，只能右键复制。是不是mac版本下的快捷键设置错了？

**Comment by compilelife** [comment]
> 日志选中也没法command + c来复制，只能右键复制。是不是mac版本下的快捷键设置错了？

大概与我删除了默认菜单有关，找个时间加回来

**Comment by itzhoujun** [comment]
别找时间啊。现在加啊大哥

**Comment by compilelife** [comment]
已修复。见v3.3.3
https://www.123pan.com/s/w9c0Vv-s3qxH.html

**Comment by itzhoujun** [comment]
确认已修复。感谢
