### ISSUE TITLE
【讨论】是否需要多标签页

### ISSUE THREAD

**Issue by compilelife** [compilelife/loginsight#4]
是否需要多标签页的功能呢？

如果只是单纯地要打开多个文件，可以开两个应用实例，分别打开即可。

多标签页可以带来什么额外的好处呢？

如果没有额外的附加好处，我认为没有必要去支持。

**Comment by bewlief** [comment]
还是有必要。例如我在2台服务器上拉下来的log，同时打开，竖直排列，两边联动，可以对比着看

**Comment by compilelife** [comment]
@bewlief 有点明白了 ，所以核心需求是能对比查看？

能再给点具体的使用场景吗？
比如，实际上是想看一份日志中的错误模式是否在另一份中存在？

界面上可能需要做些调整，目前都是以“一份日志”为主体围绕布局的

**Comment by kongminhao** [comment]
还有可能有多个模块的日志。

**Comment by compilelife** [comment]
> 还有可能有多个模块的日志。

没错！

我就发现Android上一边看traces.txt，一边看logcat是很常见的操作。

所以简单地提供多标签好像还不够，我在想能否在时间线里把两边的信息整合在一起

**Comment by compilelife** [comment]
2.0.0已经支持了多标签页
