### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by bewlief** [compilelife/loginsight#5]
- 可以选择内容的换行显示
- 可记录历史文件
- 时间线处内容的字体设置
- 程序标题栏显示当前打开的文件的路径及名称
- 时间线处的内容展示，当前只显示部分字符串，可选择是否显示全部内容；
- 可同时高亮多条不同的文字内容
- 常用操作的快捷键设置，如加入高亮，使用快捷键 ctrl+a
- 增加指定内容的数量的统计
- 时间线导出到粘贴板：不能用
- 时间线导出到图片，可显示全部内容而不是局部内容
- 时间线记录的分组：可自定义group，分组展示
- 还是以gitee为主力站点吧，github太慢了些

**Comment by compilelife** [comment]
你的建议都挺好的！

可以每条提一个issue吗？我们可以展开讨论和跟踪

**Comment by compilelife** [comment]
@bewlief  关于转战gitee：

github名气更高，且有国外用户活跃。将来有拓展到国外用户的计划，所以目前仍然以github来积累用户。

如果gitee上您有办法吸引到用户，可以考虑！

**Comment by compilelife** [comment]
"可以选择内容的换行显示"

不支持。为了支持大文件的滚动和快速处理，底层机制是以行（文件行==编辑器里的行）为单位，所以不能折行。

**Comment by compilelife** [comment]
- 可记录历史文件： 计划中
- 时间线处内容的字体设置： 暂无计划
- 程序标题栏显示当前打开的文件的路径及名称： 已支持
- 时间线处的内容展示，当前只显示部分字符串，可选择是否显示全部内容：计划中
- 可同时高亮多条不同的文字内容：已支持
- 常用操作的快捷键设置，如加入高亮，使用快捷键 ctrl+a：部分已有快捷键，见帮助菜单；其他待加入
- 增加指定内容的数量的统计：没明白意思
- ”时间线导出到粘贴板：不能用“： 无法复现
- “时间线导出到图片，可显示全部内容而不是局部内容”：无法复现
- “时间线记录的分组：可自定义group，分组展示”：具体功能形式规划中
