### ISSUE TITLE
打开文件操作优化建议

### ISSUE THREAD

**Issue by thewon86** [compilelife/loginsight#6]
讲真，被LongtimeOperation这个迷惑了，看很长时间没看懂里面的op是在什么时候初始化的，然后被应用到了进度条内。
从源码上看，打开一个文件的操作被移到一个线程内进行了。考虑到大文件打开时间长的问题，先经过500ms的QEventLoop本意打算用来响应界面操作；然后弹出一个模态对话框，***阻塞***了界面操作，从这里看前边的QEventLoop是没多大意义的，多线程也是增加了操作复杂性，同时引入了不安全性！
大胆猜测，进度对话框的私有变量 LongtimeOperation& ProgressDialog::mOp 是 LongtimeOperation BackgroundRunner::mOp 的一个引用，FileLog::open(const QString &path, LongtimeOperation& op)这个也是 LongtimeOperation BackgroundRunner::mOp 的一个引用。而最后一个open是在另外一个线程运行的！！！
建议，文件操作线程和主线程直接用信号槽进行通信，不是直接修改其它线程的变量。MainWindow::doOpenFile里面的ret也是在lambda里面在另外一个线程修改了ui线程的某个局部变量。

**Comment by compilelife** [comment]
这里的确是个可优化的地方。

整体效果只要能实现“快操作静默完成，慢操作显示进度条”就可以。

这个LongtimeOperation我们还用在了搜索、过滤等可能会耗时的地方，初衷是把这样一种行为抽象出来，让实现主要逻辑的地方只关心核心实现，并时不时“发布”下进度即可。

**Comment by thewon86** [comment]
对，但是实际操作和不用线程一个效果了。使用线程的方向是对了，也方便以后扩展，假如某天添加了tab，使用标签页打开一个文件，也可以做到这边搜索一个文件，另外同时可打开一个文件，或者去查看另外一个文件。
