### ISSUE TITLE
内存映射内存不正常修改

### ISSUE THREAD

**Issue by thewon86** [compilelife/loginsight#8]
内存映射返回的内存代码中不应该进行任何修改。结尾加 '\0' 的操作会让所有打开的文件的最后一个字符丢失！！！

**Comment by compilelife** [comment]
我在mac上试了，并不会修改文件内容。

你在什么系统试的？

我的理解是mmap我以读的方式映射进来，当我修改其内存，修改的是副本，而非实体文件。

**Comment by compilelife** [comment]
v2.0.0机制作了修改，最后一个字符不会丢失了
