### ISSUE TITLE
windows版点击loginsight.exe启动系统错误，报”由于找不到Qtcore.dll“，无法继续执行代码，重新安装程序可能会解决此问题”

### ISSUE THREAD

**Issue by cnwxzhaoyang** [compilelife/loginsight#9]
包里确实没有QtCore.dll

**Comment by compilelife** [comment]
多谢反馈，已修复。重新下v1.0的包试试看

**Comment by jijingtaifeng** [comment]
还是不行
![image](https://user-images.githubusercontent.com/13389484/104401329-ee7fc500-558e-11eb-9bdd-85fd9617080a.png)

**Comment by compilelife** [comment]
这是最新版本（v1.5.0），可以试试看
https://www.jianguoyun.com/p/DT_E62QQvKjwBhjRitkD

**Comment by compilelife** [comment]
我这边win7、win10试了都可以。

会不会下载的zip不完整？

**Comment by compilelife** [comment]
无法重现，先关了。
